### ISSUE TITLE
Logo for editing the account is not visible

### ISSUE THREAD

**Issue by Yerlix** [jamiewilson/darkside#10]
Hi

Today I've updated to a new version (in a long time) and first thin I noticed was that I can't edit my account anymore. To be more precise, the logo/image/arrow is gone at the right of my email.
Clicking still works, but I just can't see it.

An image may help explain it:
![image](https://cloud.githubusercontent.com/assets/3891388/13421325/faffc482-df8d-11e5-8145-7b66ffc51baa.png)

**EDIT**: In the console I can see that the image is not loaded:
![image](https://cloud.githubusercontent.com/assets/3891388/13421353/36994806-df8e-11e5-9aca-c0a68ced7cf1.png)

I've pulled the master branch and used that branch as the theme. Don't know if that's the correct way to update or not.

**Comment by jamiewilson** [comment]
Oops. I need to change the path to `darkside-master` there. Thanks for filing this issue. will get it fixed asap!

**Comment by jamiewilson** [comment]
Should be fixed now with the 21cfd4b commit.
