### ISSUE TITLE
Styling for multithread is of

### ISSUE THREAD

**Issue by Yerlix** [jamiewilson/darkside#12]
I just noticed that the styling for a thread with collapsed messages is not styled correctly.

![image](https://cloud.githubusercontent.com/assets/3891388/13662270/8e344680-e699-11e5-81cf-2d23eb9afd1e.png)

**Comment by jamiewilson** [comment]
Oh no. That should have been corrected with commit 3f0653c. It should look like this now:

![screen shot 2016-03-10 at 10 24 09 am](https://cloud.githubusercontent.com/assets/3308673/13676269/bbce35a4-e6aa-11e5-9eeb-b32e07ab2bfb.png)

You could `git pull` from your `~/.nylas/packages/darkside-master` directory to bring it up do date, or [download the ZIP](https://github.com/jamiewilson/darkside/archive/master.zip) again.

**Comment by Yerlix** [comment]
I've done the GIT pull. That problem is fixed like you said.

However this has popped up (or did exist already)
![image](https://cloud.githubusercontent.com/assets/3891388/13702678/a14e441c-e790-11e5-8521-7f877bf1d372.png)

I don't know if it's meant like that or not. But I think it looks better with the same width as the rest.

**Comment by jamiewilson** [comment]
Oops. I've never seen that message! I've actually reverted back to the 800px width for a number of reasons, so this issue should be fixed soon.

**Comment by Yerlix** [comment]
This is fixed with a new pull
