### ISSUE TITLE
Update bar is a little weird

### ISSUE THREAD

**Issue by louim** [jamiewilson/darkside#13]
I think it should not go over the content

<img width="1279" alt="capture d ecran 2016-03-11 a 10 32 30" src="https://cloud.githubusercontent.com/assets/923718/13706840/d8237e4c-e774-11e5-8eeb-ea410397a11f.png">

**Comment by jamiewilson** [comment]
Ah. yeah. that should be fixed soon. Thanks for reporting!

**Comment by louim** [comment]
Thanks! I noticed that since the update, Darkside is bundled with Nylas. Congrats!

**Comment by jamiewilson** [comment]
Thanks! There were some things that had to change in order for it to be included in the N1 internals, so if you catch anything else, please let me know!

**Comment by jamiewilson** [comment]
This should be fixed now! Thanks for filing and let me know if you catch anything else.
