### ISSUE TITLE
Spacing differences between latest darkside & bundled darkside

### ISSUE THREAD

**Issue by ggamel** [jamiewilson/darkside#14]
Hi,

Really liking most of the darkside theme. Solid work! 👏

I decided to fork darkside to make some personal tweaks, but the latest darkside has spacing differences compared with the bundled darkside.

See this GIF as an example: 
![darkside-difference](https://cloud.githubusercontent.com/assets/34730/13724156/98343b32-e841-11e5-8a17-87335ddb7ab4.gif)

This is just me switching between the bundled darkside and the latest repo darkside. The more generous spacing is the bundled darkside, whereas the latest repo darkside features sidebar elements closer together.

Will the updated spacing changes pass to the latest repo darkside?

**Comment by jamiewilson** [comment]
Hey.  yeah, those changes will get pulled into the N1 release at some point. Not sure yet what the timeline is for updating, but for now, the whole app needs to be updated to reflect any changes to 3rd party plugins. Hopefully in the future a package management system will allow things to update independently.

**Comment by jamiewilson** [comment]
The bundled and manual version should now be identical. Thanks for filing and let me know if you catch anything else.
