### ISSUE TITLE
UI elements hardly visible from inside e-mail

### ISSUE THREAD

**Issue by enoversum** [jamiewilson/darkside#15]
Hi @jamiewilson ,

I think your darkside theme officially became the most beautiful theme for N1 so far :wink: . 

One thing that bugs me a bit is that you can hardly see the UI elements, i.e. clicky buttons on top of an open e-mail. I haven't checked the gitted version but use the built-in one that ships with N1 now. See screenshot below :+1: . They're dark grey on dark blue/lilac/younameit :)!

![screenclip](https://cloud.githubusercontent.com/assets/8190174/13724236/c6bf4f80-e87f-11e5-8824-c8dacfd1dc8f.png)

**Comment by jamiewilson** [comment]
Hey @enoversum, thanks! Sorry about this! A couple of CSS selectors were removed from my theme when I merged it into the main N1 repo. This will be fixed soon, although I'm not sure exactly when the next version of N1 will be released.

**Comment by enoversum** [comment]
Hi @jamiewilson , there is a 'pending release', so it should not take too long :). Thanks for letting me know.
It’s a bit impractical that there is no update routine for plugins/themes yet and that baking it into N1 directly means no updates until the main app is being updated. But I am sure Nylas will get an update routine soon :).

**Comment by jamiewilson** [comment]
This should be fixed now! Thanks for filing and let me know if you catch anything else.
