### ISSUE TITLE
Linux: Compose Icon not right-aligned

### ISSUE THREAD

**Issue by mbilker** [jamiewilson/darkside#3]
Unlike the OS X version of N1, there are no "traffic lights" or window management icons built in to N1 for Linux. There is a inconsistent UX from this issue with Darkside. I really do like Darkside, but I want it to function correctly.

![2016-02-17-00-35-35_312x331](https://cloud.githubusercontent.com/assets/1266541/13100757/61769f40-d50e-11e5-8ed4-66445f83b24f.png)

**Comment by jamiewilson** [comment]
@mbilker Hey, I solved this a bit differently than you using `justify-content: flex-end`. Would you mind letting me know if this doesn't work for you?
