### ISSUE TITLE
Strange gradient on list view

### ISSUE THREAD

**Issue by patrickheeney** [jamiewilson/darkside#6]
![screen shot 2016-02-22 at 4 42 12 pm](https://cloud.githubusercontent.com/assets/1407228/13236702/4bb66086-d983-11e5-95b7-e05bc1804d4b.png)

In the two pane view with the list expanded enough to show on one line, you get this strange gradient when you hover a selected item.

**Comment by patrickheeney** [comment]
![screen shot 2016-02-22 at 4 44 26 pm](https://cloud.githubusercontent.com/assets/1407228/13236740/8eaed530-d983-11e5-9c0f-d9a6876823d1.png)

Also the important tag disappears.

**Comment by jamiewilson** [comment]
yuck. Sorry about that. Thanks for the heads-up. Will take a look at it right now.

**Comment by jamiewilson** [comment]
Let me know if this fixes everything for you! thanks again.

**Comment by patrickheeney** [comment]
It looks awesome, thank you!
