### ISSUE TITLE
New message interface

### ISSUE THREAD

**Issue by patrickheeney** [jamiewilson/darkside#7]
Just wondering if these are intentional:

![screen shot 2016-02-24 at 9 24 09 am](https://cloud.githubusercontent.com/assets/1407228/13292310/78d6a00c-dad8-11e5-9172-4bc73d0ecc13.png)

![screen shot 2016-02-24 at 9 24 21 am](https://cloud.githubusercontent.com/assets/1407228/13292311/78d73030-dad8-11e5-9e96-9d689751cb31.png)

It looks nice on the search field since it already has a border, but a bit strange on the new message dialog in my opinion.

**Comment by jamiewilson** [comment]
No, not really :) Just haven't had the time to fine-tune that, but it definitely bothers me!
