### ISSUE TITLE
New Nylas version broke the theme

### ISSUE THREAD

**Issue by louim** [jamiewilson/darkside#8]
The top bar is visible in the settings. :cry: 

Running version: `0.4.9-575c091`

<img width="1392" alt="capture d ecran 2016-02-26 a 15 30 13" src="https://cloud.githubusercontent.com/assets/923718/13364646/f91f9bbc-dc9d-11e5-81b5-c4c814dc97f7.png">

**Comment by jamiewilson** [comment]
Thanks for reporting. Gonna try and get this up to date later today or tomorrow.

**Comment by louim** [comment]
Thanks! :heart:

**Comment by crunchyintheory** [comment]
Thanks!
