### ISSUE TITLE
Highlighted compose button is too small.

### ISSUE THREAD

**Issue by crunchyintheory** [jamiewilson/darkside#9]
It's fine vertically, but it's way too skinny. Really only visible when highlighted, which is why I can't get a screenshot of it. I just updated to the new version of darkside, n1 4.10, and Windows 8.1.

**Comment by jamiewilson** [comment]
Okay. Are you referring to the compose button in the top right of the side bar, or the Send button in the compose window?

**Comment by crunchyintheory** [comment]
I'm referring to the compose button in the top left of the side bar. It's
probably on the top right on OSX.

**Comment by jamiewilson** [comment]
okay, cool, I'll see what I can do. Thanks for the help!

**Comment by crunchyintheory** [comment]
No problem!

**Comment by jamiewilson** [comment]
@rittbys dang, not sure what's going wrong with your image attachment here!

**Comment by crunchyintheory** [comment]
Oops that was because I responded from the email!

**Comment by crunchyintheory** [comment]
![capture](https://cloud.githubusercontent.com/assets/5205015/13539073/acfef25c-e213-11e5-8438-d35768ef33b0.PNG)

**Comment by jamiewilson** [comment]
@rittbys Hey, thanks for adding the screenshot. Can you explain what I'm looking at here? Did you add the grey background or is that the way the theme is rendering for you?

**Comment by jamiewilson** [comment]
@rittbys Got it. Will take a look soon.

**Comment by jamiewilson** [comment]
Hey, @rittbys, is this still an issue?

**Comment by crunchyintheory** [comment]
Now it's not highlighted at all, so I suppose it isn't. :+1:
